### ISSUE TITLE
WindowLeaked com.android.internal.policy.PhoneWindow

### ISSUE THREAD

**Issue by jnrepo** [react-community/react-native-image-picker#527]
```
03-28 16:21:04.862 27263-27263/com.test.debug E/WindowManager: android.view.WindowLeaked: Activity com.test.MainActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{6b8b757 V.E...... R....... 0,0-1026,749} that was originally added here
                                                                             at android.view.ViewRootImpl.<init>(ViewRootImpl.java:566)
                                                                             at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:326)
                                                                             at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
                                                                             at android.app.Dialog.show(Dialog.java:350)
                                                                             at com.imagepicker.ImagePickerModule.showImagePicker(ImagePickerModule.java:182)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
                                                                             at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
                                                                             at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                             at android.os.Looper.loop(Looper.java:158)
                                                                             at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                             at java.lang.Thread.run(Thread.java:818)
```

react-native: 0.42.0
react-native-image-picker: 0.26.2
platform: Android

Hi, it was working fine when react-native was 0.38, but after the upgrade pressing `Take a Photo` will crash the app on Android and throw the error above. Thanks in advanced!

**Comment by rusfearuth** [comment]
@jnrepo What were you doing with app, before it crashed?

**Comment by jnrepo** [comment]
@rusfearuth Opened my app; selected `take a photo`; and it would throw that error. I didn't see this before, maybe its because I updated my android build tools to `25.0.0`?

**Comment by rusfearuth** [comment]
@jnrepo I'm not sure about build tools. It couldn't create crash. Do you use ReactActivity or something custom?

**Comment by jnrepo** [comment]
@rusfearuth using the ReactActivity; nothing custom

**Comment by jnrepo** [comment]
@rusfearuth I've dug into the issue more and found out Its exiting with this error:

```
04-23 13:00:27.709 17561 17561 E UncaughtException: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at com.imagepicker.utils.RealPathUtil.compatUriFromFile(RealPathUtil.java:31)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:253)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at com.imagepicker.ImagePickerModule$1.onRequestPermissionsResult(ImagePickerModule.java:109)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at com.facebook.react.ReactActivityDelegate$1.invoke(ReactActivityDelegate.java:211)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:131)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at com.facebook.react.ReactActivity.onResume(ReactActivity.java:66)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1286)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at android.app.Activity.performResume(Activity.java:6987)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4144)
04-23 13:00:27.709 17561 17561 E UncaughtException: 	... 8 more
```

hmm... and looking online it seems its related to my fileprovider in my manifest. Is there a recommended way to set it up?

**Comment by jnrepo** [comment]
I was able to fix the issue. Had to change my provider to look like this... (copied directly from android manifest in `react-native-image-picker`)

```
      <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
```

**Comment by haitaoli** [comment]
@jnrepo thanks for updating this issue.

**Comment by vvavepacket** [comment]
@jnrepo 

Hi, I pasted the same provider xml inside my Android Manifest . xml of my project, yet I still get same issue. Did you do anything else aside from this to fix this?

**Comment by miracledan** [comment]
I get this error when shooting video on android 4.4.2
I debug the project and found the error in "ImagePickerModule.java"
```
public void launchCamera(final ReadableMap options, final Callback callback) {
...
if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
      List<ResolveInfo> resInfoList = reactContext.getPackageManager().queryIntentActivities(cameraIntent, PackageManager.MATCH_DEFAULT_ONLY);
      for (ResolveInfo resolveInfo : resInfoList) {
        String packageName = resolveInfo.activityInfo.packageName;
        reactContext.grantUriPermission(packageName, cameraCaptureURI, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
      }
    }
...
}
```
cameraCaptureURI is null when shooting video, so the below code will throw a exception.
`reactContext.grantUriPermission(packageName, cameraCaptureURI, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);`

I add a condition judge to fix this problem like this: 
```
if (cameraCaptureURI != null && Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT)
```
[the commit](https://github.com/qianhaikeji/react-native-image-picker/commit/275a301edddfdbeab679a6e3857ed9b95e21c7dc)

For convenience, I forked this project and commit above code. And we can use
`yarn add github:qianhaikeji/react-native-image-picker` to avoid this error.

**Comment by JoelKap** [comment]
After an about 3 hours of sweating, I added these 2 lines in AndroidManifest.xml
**<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>**

**Comment by HarshitMadhav** [comment]
@JoelKap can you share those two lines?

**Comment by abdulqadir-jugnu** [comment]
@JoelKap Can you share those 2 magical lines?
