### ISSUE TITLE
Issue with picker after migrating to RN 0.44.0

### ISSUE THREAD

**Issue by knalinne** [react-community/react-native-image-picker#578]
### Description

Since migration from RN 0.35.0 to RN 0.44, the app crash after selecting an image from the library

All I have is this stack trace: 

>java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:32)
	at com.facebook.react.bridge.PromiseImpl.resolve(PromiseImpl.java:32)
	at com.showlocationservicesdialogbox.LocationServicesDialogBoxModule.checkLocationService(LocationServicesDialogBoxModule.java:51)
	at com.showlocationservicesdialogbox.LocationServicesDialogBoxModule.onActivityResult(LocationServicesDialogBoxModule.java:80)
	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:265)
	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:675)
	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:149)
	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
	at android.app.Activity.dispatchActivityResult(Activity.java:6935)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4086)
	... 9 more

Any idea ?

Thanks for your help

### Additional Information

* React Native version: 0.44.0
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Webstorm

**Comment by knalinne** [comment]
Hello,

Problem solved, nothing to do with react-native-image-picker ...
It was another package that wasn't up to date...

Sorry !

**Comment by IgorVanian** [comment]
I have the same problem, what was your solution?

**Comment by knalinne** [comment]
Hello,

The problem I had was due to another package using native dialog.
I had to update it to solve the issue.
The package is this one: https://www.npmjs.com/package/react-native-android-location-services-dialog-box

If you don't use it, maybe you should check if all your packages using the native dialog are up to date.
