### ISSUE TITLE
crash in Android

### ISSUE THREAD

**Issue by ANDYLZH** [react-community/react-native-image-picker#708]
The first choice photo album is normal, the second choice point is determined and then refunded.

Logcat int Android Studio:
10-31 16:36:45.960 3496-3515/? I/ErrorSaveTask: LOG: keyMessage = java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://media/external/images/media/33 }} to activity {com.XXX/com.XXX.MainActivity}: java.lang.IllegalStateException: Queue full
                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3864)
                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3907)
                                                    at android.app.ActivityThread.access$1500(ActivityThread.java:169)
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:159)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5671)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                 Caused by: java.lang.IllegalStateException: Queue full
                                                    at java.util.AbstractQueue.add(AbstractQueue.java:69)
                                                    at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:282)
                                                    at com.stormorai.smartbox.MainActivity.onActivityResult(MainActivity.java:37)
                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6358)
                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3860)
                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3907) 
                                                    at android.app.ActivityThread.access$1500(ActivityThread.java:169) 
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                    at android.os.Looper.loop(Looper.java:159) 
                                                    at android.app.ActivityThread.main(ActivityThread.java:5671) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by paynd** [comment]
Same problem on one separate device:

`Exception java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=0, data=null} to activity {com.xxx/com.xxx.MainActivity}: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.`
Even on first try to pick image from gallery.

**Comment by ANDYLZH** [comment]
I have solved this problem.Because I rewrote the “onActivityResult ”method, also “mqueue.add” causes Queue full when the request is unsuccessful, just comment out.

**Comment by adamivancza** [comment]
@paynd @ANDYLZH could you share how did you managed to solve this? I just a saw a similar crash using latest version of library.

**Comment by andreasmjg** [comment]
@paynd @ANDYLZH - also interested in this. Could you expand on this? 

> I rewrote the “onActivityResult ”method, also “mqueue.add” causes Queue full when the request is unsuccessful, just comment out.

Thanks in advance

**Comment by andreasmjg** [comment]
Also @ANDYLZH what devices did you have troubles with? We are struggling with a Huawei GR3 crashing

**Comment by jindada** [comment]
+1
d: DOOGEE BL5000
version: 0.26.10

**Comment by CocoaZX** [comment]
I have to rewrote onActivityResult, how can I avoid crash?

**Comment by CocoaZX** [comment]
Ok,I can switch the requestCode

**Comment by kayzenkayzen** [comment]
some issue! Any update ??
