### ISSUE TITLE
Two pickers open, on close crashes

### ISSUE THREAD

**Issue by butchmarshall** [react-community/react-native-image-picker#760]
### Description

Call `ImagePicker.showImagePicker` twice.  This is possible in my code because initial boot produces a slice freeze.  If you tap twice during this period you can get two pickers open.

### How to repeat issue and example

Open two pickers at the same time, try and close them, app crashes.

### Additional Information

```
12-29 23:18:53.802  8879  8957 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
12-29 23:18:53.802  8879  8957 E AndroidRuntime: Process: com.snow_trails, PID: 8879
12-29 23:18:53.802  8879  8957 E AndroidRuntime: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:30)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at com.imagepicker.ResponseHelper.invokeResponse(ResponseHelper.java:76)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at com.imagepicker.ResponseHelper.invokeCancel(ResponseHelper.java:63)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at com.imagepicker.ImagePickerModule.doOnCancel(ImagePickerModule.java:201)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at com.imagepicker.ImagePickerModule$2.onCancel(ImagePickerModule.java:182)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at com.imagepicker.utils.UI$3.onCancel(UI.java:89)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1770)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
12-29 23:18:53.802  8879  8957 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:762)
12-29 23:18:53.805  3672  4626 W ActivityManager:   Force finishing activity com.snow_trails/.MainActivity
```

**Comment by haitaoli** [comment]
Thanks for reporting the issue. Even if this is fixed in the image picker (by returning appropriate error), your code still need to prevent this scenario from happening. Otherwise the user may accidentally tap the button twice and see some cryptic error.
