### ISSUE TITLE
AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'

### ISSUE THREAD

**Issue by huston007** [react-community/react-native-image-picker#882]
### Description

I've upgraded to latest React Native 0.56.0 – It also brings updates of Android build tools versions. I use latest react-native-image-picker@0.26.10
When I run android build (`react-native run-android`) it fails with this messages:

```
:react-native-image-picker:preBuild UP-TO-DATE
:react-native-image-picker:preReleaseBuild UP-TO-DATE
:react-native-image-picker:checkReleaseManifest
:react-native-image-picker:preDebugAndroidTestBuild UP-TO-DATE
:react-native-image-picker:preDebugBuild UP-TO-DATE
:react-native-image-picker:preDebugUnitTestBuild UP-TO-DATE
:react-native-image-picker:preReleaseUnitTestBuild UP-TO-DATE
:react-native-image-picker:prepareAndroidArchLifecycleRuntime100Library
:react-native-image-picker:prepareComAndroidSupportAnimatedVectorDrawable2610Library
:react-native-image-picker:prepareComAndroidSupportAppcompatV72610Library
:react-native-image-picker:prepareComAndroidSupportSupportCompat2610Library
:react-native-image-picker:prepareComAndroidSupportSupportCoreUi2610Library
:react-native-image-picker:prepareComAndroidSupportSupportCoreUtils2610Library
:react-native-image-picker:prepareComAndroidSupportSupportFragment2610Library
:react-native-image-picker:prepareComAndroidSupportSupportMediaCompat2610Library
:react-native-image-picker:prepareComAndroidSupportSupportV42610Library
:react-native-image-picker:prepareComAndroidSupportSupportVectorDrawable2610Library
:react-native-image-picker:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:react-native-image-picker:prepareComFacebookFrescoDrawee190Library
:react-native-image-picker:prepareComFacebookFrescoFbcore190Library
:react-native-image-picker:prepareComFacebookFrescoFresco190Library
:react-native-image-picker:prepareComFacebookFrescoImagepipeline190Library
:react-native-image-picker:prepareComFacebookFrescoImagepipelineBase190Library
:react-native-image-picker:prepareComFacebookFrescoImagepipelineOkhttp3190Library
:react-native-image-picker:prepareComFacebookReactReactNative0560Library
:react-native-image-picker:prepareComFacebookSoloaderSoloader030Library
:react-native-image-picker:prepareOrgWebkitAndroidJscR174650Library
:react-native-image-picker:prepareReleaseDependencies
:react-native-image-picker:compileReleaseAidl
:react-native-image-picker:compileReleaseNdk NO-SOURCE
:react-native-image-picker:compileLint
:react-native-image-picker:copyReleaseLint NO-SOURCE
:react-native-image-picker:compileReleaseRenderscript
:react-native-image-picker:generateReleaseBuildConfig
:react-native-image-picker:generateReleaseResValues
:react-native-image-picker:generateReleaseResources
:react-native-image-picker:mergeReleaseResources
:react-native-image-picker:processReleaseManifest
:react-native-image-picker:processReleaseResources
/Users/.../Documents/work/.../node_modules/react-native-image-picker/android/build/intermediates/res/merged/release/values-v26/values-v
26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

/Users/.../Documents/work/.../node_modules/react-native-image-picker/android/build/intermediates/res/merged/release/values-v26/values-v
26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.


:react-native-image-picker:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-picker:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

### How to repeat issue and example

Just try to use react-native-image-picker with latest React Native 0.56.0

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: 0.56.0
* Platform: Android
* Development Operating System: macOS
* Dev tools: 
```
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
```

### Solution

Building react-native-image-picker on the same tools version as main project helps, so I suggest using general approach of supporting passing tools version from root project:
```
def _ext = rootProject.ext;

def _compileSdkVersion = _ext.has('compileSdkVersion') ? _ext.compileSdkVersion : 25;
def _buildToolsVersion = _ext.has('buildToolsVersion') ? _ext.buildToolsVersion : '25.0.2';
def _minSdkVersion = _ext.has('minSdkVersion') ? _ext.minSdkVersion : 16;
def _targetSdkVersion = _ext.has('targetSdkVersion') ? _ext.targetSdkVersion : 25;

android {
    compileSdkVersion _compileSdkVersion
    buildToolsVersion _buildToolsVersion

    defaultConfig {
        minSdkVersion _minSdkVersion
        targetSdkVersion _targetSdkVersion
        versionCode 1
        versionName computeVersionName()
    }
    lintOptions {
        abortOnError false
    }
}
```

**Comment by SumanthPuram** [comment]
We can force Gradle to build all the dependencies with our main project SDK version and tools versions. 
Add the following line to your project's `android/build.gradle`

```

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion "27.0.2"
            }
        }
    }
}
```

**Comment by alexghinea-adswizz** [comment]
@SumanthPuram you saved my react `0.56` migration process! 🥇

**Comment by RajaSaravanan** [comment]
@SumanthPuram You saved my day bro! Works perfectly!

**Comment by abartolo** [comment]
@huston007 Your solution worked! thanks, this should be the correct answer imo.

@SumanthPuram solution did not work for me as other libraries had issue with that change.

**Comment by mdelclaro** [comment]
@SumanthPuram worked to me as well! Thank you very much. I was facing this issue when using React Native Navigation v1 and React Native 0.56. Thanks!

**Comment by korgara** [comment]
@SumanthPuram your solution helped me to generate apk, but this apk doesn't launch.
In android studio I got error like 
```
    com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 't.default')
    
    This error is located at:
        in e
        in RCTView
        in RCTView
        in n, stack:
    e@439:497
    nr@237:43523
    Ur@237:56432
    Ar@237:56864
    si@237:61708
    li@237:61128
    ii@237:60256
    Mr@237:59236
    pi@237:66432
    mi@237:66744
    render@237:69043
    exports@415:431
    run@411:611
    runApplication@411:2013
    value@98:3340
    <unknown>@98:923
    value@98:2609
    value@98:895
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:166)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by abartolo** [comment]
I created a pull request that fixes this issue so anyone migrated to React Native v56 should be good. This approach worked for me as @SumanthPuram method broke other dependencies that I am using.
 https://github.com/react-community/react-native-image-picker/pull/912

**Comment by Asinox** [comment]
Oh God, thanks @SumanthPuram !

**Comment by huston007** [comment]
@abartolo Cool, but this #912 does literally the same as my initial PR #883 = )

Anyway how could we get merged any of them?

**Comment by abartolo** [comment]
@huston007 lmao, sorry about that. I did not see your PR. I've been going around other libraries and doing the same and must have not checked. I'll close my PR now. Thanks for the update

**Comment by roziy** [comment]
@SumanthPuram Thanks,

**Comment by ruk91** [comment]
Thanks, @SumanthPuram. Your solution works fine.

**Comment by ahirag** [comment]
Thanks @SumanthPuram, helped me with v56 Migration :)

**Comment by kadirguloglu** [comment]
Thanks @SumanthPuram

**Comment by zouyu0008** [comment]
Thanks @SumanthPuram ,Get rid of the damn problem at last

**Comment by charpeni** [comment]
Thanks, it has been fixed by 8187eaf1ca308c0737ed13e96f98bd0033ca160e.

A new release should be available soon.

**Comment by dalmeria** [comment]
@SumanthPuram i love you

**Comment by flosdor** [comment]
@SumanthPuram You save me!!! THX!!

**Comment by lsantamaria** [comment]
Thanks, @SumanthPuram !. Your solution works with SDK 28 as well.

**Comment by zh-debug** [comment]
@SumanthPuram thanks
