### ISSUE TITLE
Missing android.support.FILE_PROVIDER_PATHS meta-data

### ISSUE THREAD

**Issue by jiushicheng** [react-community/react-native-image-picker#990]
* Please read the following carefully before opening a new issue.
Your issue may be closed if it does not provide the information required by this template.

--- Delete everything above this line ---

### Description

Explain what you did, what you expected to happen, and what actually happens.

### How to repeat issue and example

Your explanation here and source code or link

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by jiushicheng** [comment]
java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:587)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:558)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
        at com.imagepicker.ImagePickerModule.compatUriFromFile(ImagePickerModule.java:706)
        at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:180)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:150)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:833)
